### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by hkp108** [gvonkoss/recommend-n-chill#1]
Set up repo, and install rails-angular

**Comment by gvonkoss** [comment]
Add to README:  local installation of protractor/karma through CLI in order to run tests

**Comment by gvonkoss** [comment]
```
npm install karma --save-dev
npm install karma-jasmine karma-chrome-launcher --save-dev
npm install jasmine-core --save-dev
npm install -g karma-cli
```

**Comment by gvonkoss** [comment]
all in node_module, goes into .gitignore

might have to delete from rails-assets in gemfile

**Comment by gvonkoss** [comment]
`rake db:create`
